data:
    image_size: 256
    channels: 3

model:
    type: "simple"
    in_channels: 3
    out_ch: 3
    ch: 64
    ch_mult: [ 1, 1, 1, 2 ]
    num_res_blocks: 1
    attn_resolutions: [ 16, ]
    dropout: 0.0
    var_type: fixedlarge
    ema_rate: 0.9999
    ema: True
    resamp_with_conv: True
    padding_mode: "circular" # zeros or circular

diffusion:
    beta_schedule: linear
    beta_start: 0.0001
    beta_end: 0.02
    num_diffusion_timesteps: 1000
    mask_schedule_sig: 3

